version: '3.7'

services:
    webapp-server:
      build:
        context: .
        dockerfile: Dockerfile
      command: npm run dev
      image: myapp-server-img
      container_name: myapp-node-express
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
       - "8080:8080"
      env_file: 
       - .env
